### ISSUE TITLE
How to make bmxtranswrap repeat index in footer partition

### ISSUE THREAD

**Issue by protoism** [bbc/bmx#95]
I'm trying to create an RDD-9 compatible MXF file with ffmpeg + bmxtranswrap

The validator (baton) is complaining because it does not see an entire index in footer partition

There is this --repeat-index option, but it's only for op1a output, at least this is what I see from command line help.

So... in a command line such as this one, --repeat-index is ignored (tried to add it in a couple places...)

```
bmxtranswrap -y 09:59:45:00 --repeat-index -o complete_bmxtranswrap_repeat.mxf --repeat-index -t rdd9 complete.mxf
```

But looking at the code, I found that the option --ard-zdf-hdf does the trick:

```
bmxtranswrap -y 09:59:45:00 --repeat-index -o complete_bmxtranswrap_ard_zdf_hdf.mxf --ard-zdf-hdf --repeat-index -t rdd9 complete.mxf
```

So...
* why is --repeat-index ignored, if the functionality is there, and index repetition is (I believe) a good practice in RDD-9?
* What does --ard-zdf-hdf do more than repeating index in footer? Is there any chance that it will reduce compatibility with other broadcasters?

**Comment by philipnbbc** [comment]
I've enabled the `--repeat-index` option for RDD 9 in https://github.com/bbc/bmx/pull/96 and merged it. I might at some point make it the default as I think I agree that it would help readers to have the index available in the footer, but for now you can use the option.

The `--ard-zdf-hdf` option should be safe to use in non-German broadcasters as well. It adds the following to the base RDD 9:
* repeat the index in the footer
* reserves 2MB space (rather than 8KB) in the header (for potential header metadata updates)
* checks there are either 8 or 16 audio tracks
* Sets the Preface::IsRIPPresent property in the header metadata
* Sets the IndexTable::SingleIndexLocation, IndexTable::SingleEssenceLocation and IndexTable::ForwardIndexTable properties to false
